import { app } from 'electron';
import { UpdateManager } from './ts/updater';
import { WindowManager } from './ts/window';

/** Prevent Multiple opens when installing - https://www.electronforge.io/config/makers/squirrel.windows */
if (require('electron-squirrel-startup')) {
    app.quit();
}

/**
 * This allows TypeScript to pick up the magic constant that's auto-generated by Forge's Webpack 
 * plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on 
 * whether you're running in development or production).
 */
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

/** 
 * Handle creating/removing shortcuts on Windows when installing/uninstalling.
 */
if (require('electron-squirrel-startup')) {
    // eslint-disable-line global-require
    app.quit();
}

/**
 * This method will be called when Electron has finished 
 * initialization and is ready to create browser windows. 
 * Some APIs can only be used after this event occurs.
 */
app.on('ready', () => {
    let state = UpdateManager.getState();
    let window = WindowManager.create(MAIN_WINDOW_WEBPACK_ENTRY, MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY).get();
    window.show();
});

/**
 * Quit when all windows are closed.
 */
app.on('window-all-closed', () => {
    app.quit();
});